### ISSUE TITLE
Get only "profile" property.

### ISSUE THREAD

**Issue by TejasviTandon** [readium/r2-shared-swift#45]
I have been trying to run my project after updating the Carthage and it gives me the error saying that Drm.profile is a get only property. My code was working fine before this new commit. I am waiting to release my app on AppStore and not able to do so because of this. Can you let me know which previous version is compatible where Drm.profile is not only a get property. I tried with previous 3-4 commits but it gives me the following error-
Could not pick a version for github "Readium/r2-shared-swift", due to mutually incompatible requirements:
	"41603fa5b7e6b960e490b2a5c7f8d9b6a77bc731"
	"develop" (github "readium/readium-opds-swift")

**Comment by mmenu-mantano** [comment]
Hello,

If you're using the latest version of r2-shared-swift, you can safely remove any occurrence of
```
drm.profile = session.getProfile()
```
... as it's not needed anymore.

Are you supporting the DRM LCP to protect the books in your app?

If no, then maybe you can simply remove the code that is using this DRM object. Check out all the code that is between
```
#if LCP
...
#endif
```
... in your codebase, and you can safely remove it.


If you are actually using LCP, we are working on cleaning up r2-lcp-swift so that it's easier to integrate in the client apps. A lot of the DRM code is actually removed from the test app. You can update r2-lcp-swift to be guided through the code removal thanks to the deprecation errors.

**Comment by llemeurfr** [comment]
Before we close this issue, I want to advise @TejasviTandon to post a message to the Readium community (Readium Slack, email to the readium-dev list, or even in this issue) describing which app its company will release soon and the gain they get from this iOS reading SDK; it's always fair to offer a positive quote about software given for free by an active community. We need this to be convinced we have to go-on being active on this project.

**Comment by TejasviTandon** [comment]
hi @llemeurfr , I will send an email to Readium dev-list regarding the app which our company is going to release. Thanks for your quick response.

**Comment by mmenu-mantano** [comment]
@TejasviTandon Can you follow up on my question in regard to LCP? I would like to understand how you end up in this situation.

My guess is that you have "-DLCP" set up in the "Other Swift Flags" build settings of your app target, despite maybe not using LCP?

**Comment by TejasviTandon** [comment]
@mmenu-mantano I am using LCP production Library. This is for our epub reader app and we already have purchased LCP production license from Readium for this. I followed the r2-testapp-swift project to implement the LCP functionality in my app. It was working fine until now, but 2 days ago when i tried updating my Carthage, my project failed to build because of get only "Profile" Property error. 1 week ago also I had similar issue with other classes of Readium, that time I sent an email to Readium developers and they informed me that they are doing code cleaning and refactoring. They advised me to use the older commits in order to make my old code work. And this time too it seems that because of refactoring of existing Readium classes, old code is not working anymore.
In "Other swift Flags" i have "-D" "Cocoapods" set up.

**Comment by mmenu-mantano** [comment]
Okay then, you can either update r2-lcp-swift and follow the deprecation errors' instructions when building, or delete
```
drm.profile = session.getProfile()
```
... from your codebase if you need to build quickly.

Since the test app is undergoing some important architectural changes, I intend to make a branch starting from before those changes showing exactly the minimum code changes to upgrade r2-lcp-swift to help you with the upgrade.

**Comment by TejasviTandon** [comment]
@mmenu-mantano Okay, That would be great.

**Comment by mmenu-mantano** [comment]
@TejasviTandon Here you go, you can check out the branch r2-testapp-swift/examples/lcp-upgrade. And in particular this commit:
https://github.com/readium/r2-testapp-swift/commit/f94d8b788fc889ea64093d1bf80bb951aa075faa

I introduced a new class LCPLibraryService to hold the LCP related code, and remove the rest from AppDelegate and LibraryViewController.

However, I would wait a bit before doing the upgrade because we are still working on it and some signatures might change. We should finalize it in a matter of days or a couple of weeks. I will keep the examples/lcp-upgrade up-to-date.
